# Generated by Django 4.2.17 on 2025-01-05 22:08

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del salón')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('capacidad_min', models.PositiveIntegerField(blank=True, help_text='Número mínimo de personas recomendado.', null=True, verbose_name='Capacidad mínima de personas')),
                ('capacidad_max', models.PositiveIntegerField(verbose_name='Capacidad máxima de personas')),
                ('tiene_escenario', models.BooleanField(default=False, verbose_name='¿Tiene escenario?')),
                ('caracteristicas', models.TextField(blank=True, help_text='Por ejemplo: Libre vista, cocina, iluminación especial.', null=True, verbose_name='Características adicionales')),
            ],
        ),
    ]
