# Generated by Django 4.2.17 on 2025-01-05 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salones', '0003_alter_salon_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salon',
            name='owner',
        ),
    ]
